### ISSUE TITLE
High quality images and engaging descriptions

### ISSUE THREAD

**Issue by SebZG** [SebZG/boardwalk-games#2]
**User story**

As a Casual Gamer, I want to see high-quality images and engaging descriptions of the café's ambience and some of the available games, so I can decide if it's the right place for me to relax and have fun.

**Acceptance Criteria**

- [x] The homepage features a carousel with high-quality images of the café and game selection that rotates automatically and allows manual navigation.
- [x] Engaging descriptions of the café's ambience and available favourite games are displayed clearly and concisely within the site's content.
- [x] The homepage layout prominently features the images and descriptions in an uncluttered manner.

**Tasks**

- [x] Integrate provided high-quality images of the café and some of the available games into the website using a carousel.
- [x] Embed the provided engaging descriptions for the café's ambience and list of services available within the site's content.
- [x] Design and implement a homepage layout that prominently features the images and descriptions.
