### ISSUE TITLE
Location, contact details and opening hours

### ISSUE THREAD

**Issue by SebZG** [SebZG/boardwalk-games#3]
**User Story**

As a Prospective Customer, I need to find essential information such as location, contact details, and opening hours clearly and concisely, so I can easily plan my visit or get in touch with the café.

**Acceptance Criteria**

- [x] The website contains a dedicated section for location, contact details, and opening hours.
- [x] This section is clearly visible and accessible from all parts of the website.

**Tasks**

- [x] Design and place a section for location, contact details, and opening hours using information provided by the client.
- [x] Ensure the contact section is clearly visible and accessible from all parts of the website, adhering to common design standards.
