### ISSUE TITLE
Booking inquiry form

### ISSUE THREAD

**Issue by SebZG** [SebZG/boardwalk-games#4]
**User Story**

As a Customer, I want to book a table or join an open game night using a simple booking inquiry form, so I can easily organise a group visit or a special occasion.

**Acceptance Criteria**

- [x] A booking inquiry form for private events or game nights is easy to find, and the form is simple and easy to use.
- [x] The form includes all necessary fields to gather event details: Name, Email, Phone Number, Event Type and Message. Event types are: Reserve a table, Dungeons & Dragons, Retro Game Night, Tournament, Kids Party.
- [x] All fields on the form must be completed before the user can submit the form.
- [x] When the form is completed correctly, the user is taken to a success page.

**Tasks**

- [x] Implement a booking inquiry form on the website.
- [x] Implement HTML validation on the form to fit the requirements above.
- [x] Create a success page to direct users to after submitting the form.
