### ISSUE TITLE
Visible pricing for events and student discount

### ISSUE THREAD

**Issue by SebZG** [SebZG/boardwalk-games#5]
**User Story**

As a Student Gamer, I want to find clear information about upcoming events, pricing and student discounts, so I can plan my visit within my budget and time constraints.

**Acceptance Criteria**

- [x] Clear and accurate pricing information for events is displayed and easy to find
- [x] Student discount information stands out near pricing information

**Tasks**

- [x] Display pricing for events using the provided rate information.
- [x] Clearly display student discount information with the pricing for events.
