### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by SebZG** [SebZG/boardwalk-games#6]
**User Story**

As a Prospective Customer, I want to read testimonials and reviews from other customers, so I can gauge the experiences of others and feel more confident about visiting Boardwalk Games.

**Acceptance Criteria**

- [ ] The website includes a section dedicated to displaying customer testimonials and reviews.
- [ ] Testimonials are clearly visible and presented in a format that is easy to read and navigate.

**Tasks**

- [ ] Create a static section on the website for customer testimonials.
- [ ] Populate this section with a selection of pre-written testimonials.
