### ISSUE TITLE
Newsletter sign up form

### ISSUE THREAD

**Issue by SebZG** [SebZG/boardwalk-games#7]
**User Story**

As a Regular Customer, I want to sign up for newsletters and updates, so I can stay informed about special offers, new games, and upcoming events.

**Acceptance Criteria**

- [ ] The website contains a sign up form for the shop newsletter
- [ ] The sign up form is placed in the footer on every page, so that users can easily find it

**Tasks**

- [ ] Integrate the newsletter sign-up form into the website footer.
